version: '3'
services:
    api:
        image: mfigurski80/donate-api
        ports:
            - 8080:8080
        environment:
            - PASSWORD_SALT=default_password_salt
        volumes:
            - api-data:/data
volumes:
    api-data:
        driver: local